"""Immutable domain types shared across the signing pipeline."""

from sideloadedipa.domain.apple import (
    AppleOperation,
    AppleResource,
    AppleResourceKind,
    AppleResourcePlan,
    CertificateIdentity,
    CertificateMaterial,
    OperationDisposition,
    ProvisioningProfile,
)
from sideloadedipa.domain.bundle import BundleGraph, BundleNode, BundleNodeKind
from sideloadedipa.domain.common import Diagnostic, DiagnosticSeverity, FrozenJsonValue
from sideloadedipa.domain.config import (
    BundleRule,
    EntitlementMode,
    EntitlementPolicy,
    IdentifierStrategy,
    ProfileType,
    R2Config,
    SigningPolicy,
    SourceConfig,
    SourceKind,
    Task,
    TaskConfiguration,
    UnknownProfileBundlePolicy,
)
from sideloadedipa.domain.identifiers import (
    BundleIdentifierMapping,
    derive_identifier_mappings,
    derive_target_bundle_id,
    validate_bundle_identifier,
)
from sideloadedipa.domain.pipeline import (
    PipelineStage,
    PublicationResult,
    SourceAsset,
    StageState,
    StageStatus,
    StoredArtifact,
    VerificationFinding,
    VerificationResult,
)
from sideloadedipa.domain.signing import (
    SigningBackendIdentity,
    SigningNodePlan,
    SigningNodeResult,
    SigningPlan,
    SigningResult,
)

__all__ = [
    "AppleOperation",
    "AppleResource",
    "AppleResourceKind",
    "AppleResourcePlan",
    "BundleGraph",
    "BundleIdentifierMapping",
    "BundleNode",
    "BundleNodeKind",
    "BundleRule",
    "CertificateIdentity",
    "CertificateMaterial",
    "Diagnostic",
    "DiagnosticSeverity",
    "EntitlementMode",
    "EntitlementPolicy",
    "FrozenJsonValue",
    "IdentifierStrategy",
    "OperationDisposition",
    "PipelineStage",
    "ProfileType",
    "ProvisioningProfile",
    "PublicationResult",
    "R2Config",
    "SigningBackendIdentity",
    "SigningNodePlan",
    "SigningNodeResult",
    "SigningPlan",
    "SigningPolicy",
    "SigningResult",
    "SourceConfig",
    "SourceAsset",
    "SourceKind",
    "StageState",
    "StageStatus",
    "StoredArtifact",
    "Task",
    "TaskConfiguration",
    "UnknownProfileBundlePolicy",
    "VerificationFinding",
    "VerificationResult",
    "derive_identifier_mappings",
    "derive_target_bundle_id",
    "validate_bundle_identifier",
]
